### ISSUE TITLE
Is it suitable for refinning bins

### ISSUE THREAD

**Issue by Microbion** [linxingchen/cobra.github.io#2]
I read the [paper](https://doi.org/10.1101/2023.05.30.542503). In discussion you mentioned that "COBRA can also be applied to microbial genomes and whole metagenonmes" and "using COBRA only to extend the subset of longer contigs". How about to use COBRA as a binning refiner? Although some refiner has been reported, such as https://github.com/dparks1134/RefineM and https://apcamargo.github.io/magpurify2, purifing bins is difficult in extremely complex microbial community. Maybe COBRA have more performance as a binning refiner.

**Comment by linxingchen** [comment]
Hi, I replied in the thread. Please check.

Thank you.

Best,
LinXing


LinXing Chen, Ph.D.
Associated Project Scientist,
The Banfield Lab,
University of California, Berkeley, USA 94706
Phone: (1)510-701-7864
Email: ***@***.***

在 2023年6月4日 -0700 PM8:23，Jocker ***@***.***>，写道：

**Comment by linxingchen** [comment]
> Hi @linxingchen. In my opinion, whether a contig belongs to genome A or genome B needs not only overlaps but also other evidences, such as TNF(tetranucleotide frequency) , coverage , phylogenetic assignment and single marker genes. I will use classical refinement tools, like metawrap refinement module at first, then result bins which have low completeness are polished by COBRA (because the reassemble step usually decrease completness, can COBRA be the replacer?).

I have no idea how metawrap works but sounds like there is a reassemble step, could you explain more? When you said "reassemble step usually decrease completeness", I thought it was a step of assembling the mapped reads.

For a given bin, COBRA will join the contigs by their validate end overlap (maxK or maxK-1), sometimes using very small contigs that may not be in the bin, to get longer sequences. So COBRA does not use mapped reads for reassembly.

**Comment by Microbion** [comment]
Yes, the reassemble step is to used PE reads mapped to one bin. We used this after refinement module, but usually got a poor result acoording to checkm. So I'd like to replace the reassemble step by COBRA for bins quanlity improvement, although they have distinct different algorithms.

**Comment by linxingchen** [comment]
> Yes, the reassemble step is to used PE reads mapped to one bin. We used this after refinement module, but usually got a poor result acoording to checkm. So I'd like to replace the reassemble step by COBRA for bins quanlity improvement, although they have distinct different algorithms.

Right, "reassembly of mapped reads won't get better genomes", that's a lesson we learned years ago. It should be great to use COBRA for that step if the refinement step is good enough.
