### ISSUE TITLE
Cobra prints contig names and numbers without providing any clarification of what they represent

### ISSUE THREAD

**Issue by apcamargo** [linxingchen/cobra.github.io#4]
Hi @linxingchen 

I've noticed that sometimes COBRA prints contig names and numbers on the screen without a clear explanation of what they represent. It appears that the code in [these lines](https://github.com/linxingchen/cobra.github.io/blob/6422e452e37e3b9e299d6b0f07c013272dde9e9d/cobra.py#L285-L286) is responsible for this. Could it be leftover debug code?

**Comment by linxingchen** [comment]
Hi,

Thank you so much for letting me know. You can modify it to use "pass" here, it is a rare case that I tested but forgot to delete. Or you can print it to the debug file.

I hope this helps.

Have a good day.

LINXING

**Comment by apcamargo** [comment]
How rare is it, in your experience? I'm processing a single sample and more than 30 cases (for now) were identified

**Comment by linxingchen** [comment]
This is to test if there are repeats (for example, transposons) in the genomes, which means the corresponding contig of "target" should have twice or higher coverage of the query contig. In this case, the query contig can join the "target" contig, but it is difficult to determine which contig should be merged with the other end of the "target" contig, we thus ask COBRA to stop here to avoid any chimera. 

Do your queries contain a lot of non-viral contigs?

**Comment by apcamargo** [comment]
It makes sense, then. Yes, I'm testing out an entire assembly.

**Comment by linxingchen** [comment]
> It makes sense, then. Yes, I'm testing out an entire assembly.

OK. Good to know. Should be rare for viruses.
