### ISSUE TITLE
BLAST options error: File blastdb_1.fa is empty

### ISSUE THREAD

**Issue by GLomics** [linxingchen/cobra.github.io#6]
Hi there, 

I'm excited about the potential this tool offers!  

Currently, I'm receiving an error in the python command about the BLAST db COBRA needs:

```
$ python cobra.py 
-f final.contigs.renamed.fa /
-q samp_471_concoct_280.fa /
-c coverage_tail.txt /
-m final.contigs.renamed.sam /
-a megahit /
-mink 21 /
-maxk 99
```
**Command line error:** 
```
Building a new DB, current time: 06/30/2023 13:24:18
New DB name:  samp_471_concoct_280.fa_COBRA/blastdb_1.fa
New DB title:  blastdb_1.fa
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
BLAST options error: File blastdb_1.fa is empty
BLAST Database error: No alias or index file found for nucleotide database [blastdb_1.fa] in search path [samp_471_concoct_280.fa_COBRA::/reference-data/blast:]
```

Any guidance would be greatly appreciated.

**Comment by linxingchen** [comment]
Hi, thank you for your interest in COBRA.

Usually, if the blastdb is empty, it means that COBRA got nothing joined. Could you please let me know the size of the file "COBRA_end_joining_pairs.txt"? 

I noticed that your input fasta file (-f) is with "renamed" in the name, and the query fasta file is without, please ensure that the -q fasta is a subset of the -f fasta file, and the sequence names should be the same, and this is true for the sequence names in the coverage and mapping file.

Please let me know.

Thanks.
LINXING

**Comment by GLomics** [comment]
Hi Linxing,

COBRA_end_joining_pairs.txt is 869K

Good check on the input files - the query is definitely sourced from the renamed fasta file.  The sequence names should also agree across all files.  

Thanks for the quick response.  

~Paul

**Comment by linxingchen** [comment]
Hi Paul,

How many sequences are there in your query fasta file, please?

**Comment by GLomics** [comment]
There are 990 contigs in the query.  It's a cyanobacteria bin

**Comment by linxingchen** [comment]
OK. Are they with low sequencing coverage? And could u please send me the debug file?

2023年6月30日 -0700 PM1:16 GLomics ***@***.***>，写道：

**Comment by GLomics** [comment]
The query has good sequencing coverage in general.  I can get stats on this if you'd like.

Here's the debug file:
[debug.txt](https://github.com/linxingchen/cobra.github.io/files/11923120/debug.txt)

**Comment by GLomics** [comment]
For sequencing coverage of the query:
Average - 81x
Max - 453x
Min - 3.66x

**Comment by linxingchen** [comment]
Hi Paul,

I have checked the debug file, it looks like nothing from the query fasta file has been joined. Given that the COBRA_end_joining_pairs.txt file is not very big, I hope you could confirm if the maxK is correct.

Best,
LINXING

**Comment by GLomics** [comment]
Hi LINXING,

Thanks once again for your continued help on this.  

Megahit was run using the meta-sensitive present: --k-list 21,31,41,51,61,71,81,91,99, which matches the maxk and mink I used.  

I can go through an overview of my workflow for coverage and mapping files, just incase there are any red flags.  

Coverage was generated by:
```
$ coverm contig --coupled decon_fwd_reads_fastp.fastq.gz decon_rev_reads_fastp.fastq.gz --reference final.contigs.renamed.fa -t 50 > coverm/coverage.txt
$ tail -n +2 coverage.txt > coverage_tail.txt
```

Mapping was generated by:
```
$ bowtie2-build final.contigs.renamed.fa final.contigs.renamed
$ bowtie2 -x final.contigs.renamed -1 decon_fwd_reads_fastp.fastq.gz -2 decon_rev_reads_fastp.fastq.gz -p 50 -S final.contigs.renamed.sam
31554219 reads; of these:
  31554219 (100.00%) were paired; of these:
    31514984 (99.88%) aligned concordantly 0 times
    15913 (0.05%) aligned concordantly exactly 1 time
    23322 (0.07%) aligned concordantly >1 times
    ----
    31514984 pairs aligned concordantly 0 times; of these:
      29889 (0.09%) aligned discordantly 1 time
    ----
    31485095 pairs aligned 0 times concordantly or discordantly; of these:
      62970190 mates make up the pairs; of these:
        43721052 (69.43%) aligned 0 times
        10190195 (16.18%) aligned exactly 1 time
        9058943 (14.39%) aligned >1 times
30.72% overall alignment rate
```

**Comment by linxingchen** [comment]
Hi again,

I would suggest you try several things,

(1) run another sample you have using COBRA to see if the same issue will happen again?

(2) re-run the mapping. I have no clue why the number of reads is odd (31554219). And you could use https://github.com/bcthomas/shrinksam to see how many of the reads are actually mapped, which saves you storage room as well.

**Comment by GLomics** [comment]
Hi LINXING,

I've been working on this off and on for the past week and still haven't been able to get it to work.  I'll list the troubleshooting steps I've taken here and lastly a question that may help narrow down the issue.  

1.) I ran another sample and bin using COBRA with the same error persisting 
2.) Originally, I was running everything on a server.  I setup a new environment on my personal laptop and the same error also appeared.
3.) I ran shrinksam on a new mapping file.  Same error appears.
Notes: The reads being odd number makes sense here in that I believe it refers to the number of _paired_ reads.  The next line states: 31554219 (100.00%) were paired; I agree the phrasing is confusing.  

I'm starting to wonder if the version of blast could be a cause.  I'm running:
```
$ blastn -version
blastn: 2.14.0+
Package: blast 2.14.0, build Apr 27 2023 17:10:15
```

**Comment by linxingchen** [comment]
> Hi LINXING,
> 
> I've been working on this off and on for the past week and still haven't been able to get it to work. I'll list the troubleshooting steps I've taken here and lastly a question that may help narrow down the issue.
> 
> 1.) I ran another sample and bin using COBRA with the same error persisting 2.) Originally, I was running everything on a server. I setup a new environment on my personal laptop and the same error also appeared. 3.) I ran shrinksam on a new mapping file. Same error appears. Notes: The reads being odd number makes sense here in that I believe it refers to the number of _paired_ reads. The next line states: 31554219 (100.00%) were paired; I agree the phrasing is confusing.
> 
> I'm starting to wonder if the version of blast could be a cause. I'm running:
> 
> ```
> $ blastn -version
> blastn: 2.14.0+
> Package: blast 2.14.0, build Apr 27 2023 17:10:15
> ```

Hi Paul,

I am sorry to hear that it is still not working for you. First, I do not think the blastn version is the problem. because I have the same version as you.

`blastn -version
blastn: 2.14.0+
 Package: blast 2.14.0, build Apr  5 2023 12:25:48`

A quick way to check for the problem is looking at the debug.txt file, if the last extended_circular_query and extended_partial_query are both empty (and query2current should be empty as well), it means nothing is joined, then it is correct that the blast db will be empty as well. If they are not empty and you are still getting the same error, I suggest you share me the files from one of your tested samples, let me run it on my end and see what will happen. Please let me know.

Thank you for your patience in using COBRA. I really hope it will help.

LINXING

**Comment by GLomics** [comment]
Hi LINXING,

Thank you for your support.  I tried it on a third sample and it works!  

Appreciate the help :)

**Comment by linxingchen** [comment]
> 

Thanks for the update, Paul. Glad to know that. 

Cheers,
LINXING

**Comment by dsfchina** [comment]
The same problem was encountered and is not currently resolved

**Comment by linxingchen** [comment]
> The same problem was encountered and is not currently resolved

Please check my conversation with Paul above and see if you are in the same case, that is your query list is small, if not, try several more samples to see if it works. Paul's issue has been solved obviously.

**Comment by dsfchina** [comment]
Yes!! I added more queries to the list, and now it's running successfully. I spent a lot of time, but I didn't realize on my own that I needed to add a sufficient number of queries, until you gave me the hint. Maybe some hints should be added to the software introduction page.

**Comment by linxingchen** [comment]
> Yes!! I added more queries to the list, and now it's running successfully. I spent a lot of time, but I didn't realize on my own that I needed to add a sufficient number of queries, until you gave me the hint. Maybe some hints should be added to the software introduction page.

Sounds good. I will add a "if" function there to get rid of such issues. Thanks.
