### ISSUE TITLE
DTRs and ITRs

### ISSUE THREAD

**Issue by bhimbbiswa** [linxingchen/cobra.github.io#7]
Hi.

After your suggestion last time, I reassembled my data with metaSpades (single assembly) using (-k 21,33,55,77,99,127).

From the output assembly, I filtered viral contigs using Vibrant (1983 putative phages were identified).

From here I fed these predicted phages into vRhyme and COBRA

This is the result of vRhyme for circular contigs.

```
Scaffold	type	mismatches	length	repeat
NODE_31851_length_2369_cov_1.518733	DTR	0	127	CCTCCATCAAGATGAATACAACTCCATTTACCAAGATTGTTGGCAAAATAGCTGTCATCCTCGGCAAAATTGAAACTGTCATGCACAAAGACAGCTACGCGCGTCACAGTAATGCGCCAGCGCCCAT
NODE_18158_length_3813_cov_11.723820	DTR	0	127	TAGCCGGTTGCTCTGGCACCTCTCGTACCGGCTCCTGCTTCACCCGCAGAGGGTTGATGTCCCGGCCCGAAAGGATGTAGTCCCCCGCGCCGAATCGCCAGCGGAAGGTAACCGCCAGTTCCGCCAC
NODE_14185_length_4746_cov_1.590171	DTR	0	127	ACTTCTGTTTAAATTCTTCTTTGTTAATATTTGTGTACCAGCCCCATCCATTGTAATCATGTCCGCCTGTCAAATGGTATGCTCTTTTTAATGAAGTATAATTCCCTGAAAGATGGACGCCTGTAAT
NODE_421_length_73347_cov_5.589907	ITR	0	116	GGATTGCCACCAGATATGACAAATTGGATACGTCTTTTCTCGCCTTCGTTTATATTGCCGCTATCGCTATTTTGTTAATTTAGCTCATCCCTCCTTATTTTTCAAACAACCCCTAA
NODE_4030_length_14370_cov_3.630134	DTR	0	40	ATAGAAAATAGAATAAAAAACTCATTTGTCACATGAAAAA
NODE_18745_length_3708_cov_3.479754	ITR	1	111	AAATATTTCCGATATCTATCAAAACAAAAGCGGTGGCGAATCAATCAAAACGAAGCGTTTCATACAGCAATTTTACCAGGGCTTTTGTCTTAAGTTCGCGCCTATGGGGCT
```

COBRA identified only 2 circular contigs
```
SeqID	Length	Coverage	GC	Ns	DTR_length	
NODE_31851_length_2369_cov_1.518733_self_circular	2369	10.331	57.957	0	127	
NODE_18158_length_3813_cov_11.723820_self_circular	3813	77.942	57.383	0	127	
```

COBRA even extended one circular contig as "COBRA_category_ii-b_extended_partial_unique"
```
SeqID	Length	Coverage	GC	Ns	
NODE_421_length_73347_cov_5.589907_extended_partial	88998	38.204	57.323	0	
```
Rest are "COBRA_category_ii-c_extended_failed"
```
SeqID	Length	Coverage	GC	Ns
NODE_4030_length_14370_cov_3.630134	14370	24.458	53.598	0	
NODE_18745_length_3708_cov_3.479754	3708	22.521	53.479	0
```
and "COBRA_category_iii_orphan_end"
```
SeqID	Length	Coverage	GC	Ns
NODE_14185_length_4746_cov_1.590171	4746	10.854	35.04	0
```

So, here are my questions
1) Is it possible for COBRA to identify all DTRs and ITRs?
2) As COBRA extended one of the vRhyme predicted circular contig, how should I interpret COBRA result? Is it correct to be extended by COBRA?
2) VIBRANT output is sometimes fragmented contigs whose name is not present in my assembly. These names are not recognised by COBRA. Is there any way for these fragments to be included? (In this sample there are 73 query)
```
Query NODE_464_length_69899_cov_2.489623_fragment_1 is not in your whole contig fasta file, please check!
```

**Comment by linxingchen** [comment]
Hi,

Thank you for the questions, and sorry for my delayed reply as I was on vacation last week.

1. Unfortunately, COBRA does not identify ITRs, which is not related to the basic principle of how it was developed. However, COBRA does identify DTRs for those `orphan_end` contigs.

2. Could you please share with me all these six contigs, and also the files of `COBRA_end_joining_pairs.txt` and `COBRA_potential_joining_paths.txt`? I am really interested to check `NODE_421` and `NODE_14185`. I do not understand why COBRA reported it as `orphan_end` while vRhyme was able to find a DTR of 127 bp (I guess vRhyme allows some mismatches, that's not good if so).

3. you could modify the name by using 
`sed 's/_fragment_/\t/g' file.fasta >file.fasta.1`
`cut -f1 file.fasta.1 >file.fasta.2`
then use `file.fasta.2` as the query input file.

Really appreciate all your tests and questions, I have been responding to Reviewers' comments, and I believe your experience of using COBRA will help me a lot. Thanks again.

Best,
LINXING

**Comment by bhimbbiswa** [comment]
Dear Linxing,

Thank you for your kind reply and help.

I have sent the requested file through email (to the email address in your GitHub bio).

Regarding your help with question 3. I was wondering as "Coverage.txt" has coverage of the whole contig but now my query contig doesn't have the full sequence, I hope this will not have any influence on the output of COBRA.

Regards,

Bhim

**Comment by linxingchen** [comment]
Hi Bhim,

No worries about the queries, COBRA only needs the names from this file, and will use the sequences from the whole assembly results. In the future vision, COBRA could use a query file that only contains the names, does not have to be a fasta file. 

Best,
LINXING

**Comment by linxingchen** [comment]
Hi Bhim, 

I am checking your sequences, first below is about NODE_14185, which was identified as "orphan_end" contig by COBRA while circular by vRhyme. I checked for DRT with a minimum length of 50 bp, however, I found nothing. I did find the left end of 127 bp is identical to another 127 bp in the middle of the sequence, I am afraid vRhyme is making an error here to assign a sequence with such a feature as circular. 

<img width="1081" alt="image" src="https://github.com/linxingchen/cobra.github.io/assets/46725273/76bb1479-6759-40c1-a346-911a4a9491c0">

I will update the information on other sequences soon.

Best,
LINXING

**Comment by linxingchen** [comment]
Regarding NODE_421, which was extended by COBRA (to a partial genome not circular though), but identified as a circular genome by vRhyme.

1. I check the `COBRA_end_joining_pairs.txt` file and found NODE_421 could be joined with NODE_5745, please check if NODE_5745 is a viral contig or not (it could be a host contig though). And please share with me if possible.
2. I used checkv 0.6 for the completeness of NODE_421, which has a viral length of ~60kbp, checkv estimated completeness is 84.65%, see below
<img width="1875" alt="image" src="https://github.com/linxingchen/cobra.github.io/assets/46725273/4f20f672-3ea6-440d-9f48-31f71ffabf9b">
I thus believe that it is not a circular contig.

Best,
LINXING

**Comment by linxingchen** [comment]
Regarding NODE_4030, which failed to be extended by COBRA but was identified by vRhyme as a complete genome with DTR of 40bp.

1. the 40 bp DTR is true, but there is longer repeat in the ends of the contig as well, see below

<img width="1094" alt="image" src="https://github.com/linxingchen/cobra.github.io/assets/46725273/7b9c23ec-e61e-496f-ad08-2e3ce29bf430">

2. If you believe checkv, which gives a completeness estimate of 12.6% 

<img width="1868" alt="image" src="https://github.com/linxingchen/cobra.github.io/assets/46725273/c987180c-a2b9-4f94-b4b9-dc989fc9f5ad">

3. given that the right end of NODE_4030 shares 127 bp region with another short contig, I do not believe the 40 bp DTR suggests it a circular genome

<img width="651" alt="image" src="https://github.com/linxingchen/cobra.github.io/assets/46725273/21b809d9-e4ee-447e-9bb7-a7fcd9f7ef16">

Best,
LINXING

**Comment by linxingchen** [comment]
Regarding NODE_18745, which failed to be extended by COBRA but was identified by vRhyme as a complete genome with an ITR of 111 bp.

1. It does not have an ITR of 111 bp, but two identical parts (56 bp and 54 bp) at its two ends.
<img width="1096" alt="image" src="https://github.com/linxingchen/cobra.github.io/assets/46725273/7cd271c6-5b3a-449a-9f3c-d9dffd7aff80">

2. checkv reported estimated completeness of < 10%
<img width="1871" alt="image" src="https://github.com/linxingchen/cobra.github.io/assets/46725273/e6a61cd2-93ad-4673-b666-ceeaa7139b9b">

3. the right end of NODE_18745 share the 127 bp region with another short contig, but their coverages are not similar, thus COBRA did not join them
<img width="649" alt="image" src="https://github.com/linxingchen/cobra.github.io/assets/46725273/839b7ece-c953-4459-8ce6-9807942f25b0">

I thus believe COBRA is correct here, it should not be a complete genome.

Best,
LINXING

**Comment by linxingchen** [comment]
Please let me know if you have further questions regarding these contigs, I am happy to discuss more.

Cheers,
LINXING

**Comment by bhimbbiswa** [comment]
Dear Linxing,

Thank you for your kind help. I apologise for the late reply, I was away for a conference. 

Your help has made a lot of things clear to me and has helped to improve my research.

Thank you very much.

I will share "NODE_5745" with you through email.

Regards,

Bhim

**Comment by linxingchen** [comment]
update on "NODE_5745", which looks like a host contig to me based on the high similarity of genes to those from bacteria at NCBI. So I will say a viral contig of NODE_421 joins with the host contig of NODE_5745, indicating the corresponding virus could exist in the sample primarily as a prophage. I hope this helps.

**Comment by bhimbbiswa** [comment]
Dear Linxing,

Thank you for your kind help and guidance.

I will close this for now. If I have any more issues, I will open a new issue.

Regards,

Bhim

**Comment by linxingchen** [comment]
great. thank you.
2023年8月24日 -0700 PM5:34 Bhim B Biswa ***@***.***>，写道：
